wandb_version: 1

activation:
  value: sigmoid
batch_size:
  value: 32
dataset:
  value: mnist
epochs:
  value: 20
hidden_size:
  value: 128
learning_rate:
  value: 0.002
loss:
  value: mse
num_layers:
  value: 1
optimizer:
  value: nag
weight_decay:
  value: 1.0e-05
weight_init:
  value: xavier
